create table price_tag_elec_syn
(
   id                   bigint not null auto_increment comment 'ID',
   syn_id               varchar(32) not null comment '同步ID',
   create_time          varchar(19) not null comment '创建时间',
   syn_status           smallint not null default 0 comment '同步状态(0新生成1已发成功2已发失败)',
   fail_times           smallint not null default 0 comment '失败次数',
   fail_msg             varchar(255) comment '失败信息',
   sales_shop           varchar(4) not null comment '销售门店',
   sku_id               int not null comment '商品SKUID',
   sales_org            varchar(4) comment '销售组织',
   std_price_change_time varchar(19) not null comment '标准价变价时间',
   std_price            int not null default 0 comment '标牌价',
   std_price_seq        varchar(64) not null comment '标牌价流水号',
   shop_price_change_time varchar(19) not null comment '门店价变价时间',
   shop_price           int not null default 0 comment '门店价',
   shop_price_seq       varchar(64) not null comment '门店价流水号',
   shop_price_type      varchar(4) not null comment '门店价格类型',
   promo_price_begin_time varchar(19) comment '活动价开始时间',
   promo_price_end_time varchar(19) comment '活动价结束时间',
   price_controller     varchar(16) comment '物价员',
   sku_info_change_time varchar(19) not null comment '商品信息更新时间',
   sku_name             varchar(255) not null comment '商品名称',
   sku_sales_point      varchar(255) comment '商品卖点',
   sku_spec             varchar(100) comment '商品规格',
   sku_grade            varchar(20) comment '商品等级',
   sku_size             varchar(120) comment '商品尺寸',
   sku_made_in          varchar(20) comment '商品产地',
   sku_unit             varchar(10) comment '计量单位',
   qr_code_url          varchar(255) comment '二维码URL',
   paidup_vip_change_time varchar(19) comment '付费会员更新时间',
   paidup_vip_label     varchar(20) comment '付费会员标签',
   paidup_vip_disc      varchar(10) comment '付费会员折扣',
   promo_change_time    varchar(19) comment '促销更新时间',
   promo_info           varchar(255) comment '促销信息',
   warranty_change_time varchar(19) comment '延保更新时间',
   warranty_info        varchar(255) comment '延保信息',
   instalment_info      varchar(255) comment '分期付款信息',
   last_update_time     datetime(3) not null comment '最后更新时间',
   primary key (id)
) comment '电子价签同步';
